version: '3.8'

services:
  kubectl-mcp-server:
    build: .
    container_name: kubectl-mcp-server
    ports:
      - "8000:8000"
    environment:
      - KUBECONFIG_B64=${KUBECONFIG_B64}
    volumes:
      - ./manifests:/app/manifests
      - ./scripts:/app/scripts
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3